### ISSUE TITLE
Feedback Sprint 1 Datadashboard

### ISSUE THREAD

**Issue by nerdale** [RaquelGlez/cdmx-2018-06-bc-core-am-data-dashboard#3]
Hola @RaquelGlez y Compañera
He estado revisando el proyecto y tengo algunos comentarios:

1. @RaquelGlez  debes agregar como colaboradora a **DianaOlvera**, es extremadamente necesario pues los issues van guiados hacia ambas.

2. De la mano del punto anterior veo que no realizaron los issues y milestones correspondientes al sprint 2 del proyecto, que pasó con eso?

3. Buen trabajo y completo de investigación del usuario, se nota la dedicación e interés en saber las necesidades exactas del usuario, las felicito muchisisisisimo :clap: 

4. Si bien ya pueden listar las sedes y hacer un llamado fetch, les recomiendo comenzar a trabajar con la data a profundidad lo antes posible (se encontrarán con toda la lógica para jalar la información y hacer los cálculos) y plasmar tanto visual como funcionalmente lo que tienen pensado para el proyecto.

5. Recuerden utilizar HTML semántico `<header></header> <section></section> <aside></aside> <footer></footer> <article></article>`

Vamos chicas! a darlo todo :smile: :heart:

**Comment by RaquelGlez** [comment]
Alexandra, muchas gracias por los comentarios.
Los aplicaremos cuanto antes.

**Comment by nerdale** [comment]
Perfecto, daré por cerrado el issue :smile: 
:rocket:
